CREATE TABLE "dumbphone_drawing" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dumbphone_drawing_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(256) NOT NULL,
	"imageData" text,
	"caption" text,
	"generatedImageUrl" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "dumbphone_suggestion" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dumbphone_suggestion_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"drawingId" integer NOT NULL,
	"visitorId" varchar(256),
	"suggestion" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "user_idx" ON "dumbphone_drawing" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "drawing_idx" ON "dumbphone_suggestion" USING btree ("drawingId");